### ISSUE TITLE
class-methods-use-this

### ISSUE THREAD

**Issue by igorkamyshev** [solid-soda/eslint-config#2]
I try to implement simple service, but...

<img width="243" alt="screen shot 2018-08-02 at 10 15 10" src="https://user-images.githubusercontent.com/26767722/43568360-12270c02-963d-11e8-99a9-38727910598d.png">

I guess, this rule is so strange.

**Comment by Uncleseneca** [comment]
I dont understand it too

**Comment by Uncleseneca** [comment]
1760ad9cdaa158e6459995e22a02c9b22cdc92e5
