### ISSUE TITLE
no-restricted-syntax

### ISSUE THREAD

**Issue by igorkamyshev** [solid-soda/eslint-config#3]
<img width="389" alt="screen shot 2018-08-02 at 15 40 14" src="https://user-images.githubusercontent.com/26767722/43584183-6005d002-966a-11e8-83f6-08d7f3db68a4.png">

Why? I want to use `for of`! 🙁

**Comment by Uncleseneca** [comment]
'For of' to the masses!

**Comment by Uncleseneca** [comment]
1760ad9cdaa158e6459995e22a02c9b22cdc92e5
