### ISSUE TITLE
object-curly-newline

### ISSUE THREAD

**Issue by igorkamyshev** [solid-soda/eslint-config#4]
<img width="265" alt="screen shot 2018-08-03 at 14 19 23" src="https://user-images.githubusercontent.com/26767722/43640361-50d7768a-9728-11e8-8dea-1fad98b45b3a.png">

It's bad rule, I guess. May you remove it from config?

**Comment by Uncleseneca** [comment]
Sure!

**Comment by Uncleseneca** [comment]
1760ad9cdaa158e6459995e22a02c9b22cdc92e5
